[package]
name = "yahs"
version = "0.4.0"
description = "High Altitude Balloon simulation plugin for Bevy"
edition = "2021"
authors = { workspace = true }
license = { workspace = true }

[dependencies]
bevy = { workspace = true }
avian3d = { workspace = true }

[features]
default = [
    "dev",
]
dev = [
    "bevy/dynamic_linking",
]
log = []
