[package]
name = "buoy-ui"
version = "0.1.0"
description = "UI for the Buoy simulator"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
default-run = "buoy-ui"

[[bin]]
name = "buoy-ui"
path = "src/main.rs"

[dependencies]
buoy-common = { path = "../buoy-common" }
buoy-physics = { path = "../buoy-physics" }
bevy = { workspace = true, features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_pbr",
    "bevy_text",
    "bevy_window",
    "bevy_winit",
    "bevy_gizmos",
    "bevy_picking",
    "bevy_mesh_picking_backend",
    "default_font",
    "tonemapping_luts",
    "x11",
    "wayland",
] }
avian3d = { workspace = true }
big_space = { workspace = true, optional = true,features = [ "camera" ] }
bevy-inspector-egui = { version = "0.31.0", optional = true, features = [
    "highlight_changes",
] }
bevy_egui = { version = "0.34.1", optional = true }

[features]
default = ["dev", "egui"]
dev = [
    "buoy-common/dev",
    "buoy-physics/dev",
    "bevy/dynamic_linking",
    "avian3d/debug-plugin",
    "bevy/bevy_dev_tools",
]
egui = [ "bevy_egui" ]
grid_space = [
    "buoy-common/grid_space",
    "buoy-physics/grid_space",
    "big_space",
    "big_space/debug",
]
inspect = [ "bevy-inspector-egui" ]
