[package]
name = "buoy-physics"
version = "0.4.0"
description = "Physics engine and runtime for the Buoy simulator"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
default-run = "buoy"

[[bin]]
name = "buoy"
path = "bin/main.rs"

[dependencies]
glam = { workspace = true }
uom = { workspace = true }
serde = { workspace = true }
log = { workspace = true }
bevy = { workspace = true, features = ["bevy_asset"], optional = true }
bevy_common_assets = { workspace = true, optional = true }
bevy_repl = { version = "0.3.0", features = ["derive"], optional = true }

[features]
default = [
    "bevy",
    "dev",
]
bevy = ["dep:bevy", "dep:bevy_common_assets", "dep:bevy_repl"]
dev = [
    "bevy/dynamic_linking",
    "bevy/bevy_debug_stepping",
]


# [package.metadata.mutually_exclusive_features]
