[package]
name = "buoy-core"
version = "0.1.0"
description = "Application for the Buoy simulator"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
default-run = "buoy"

[[bin]]
name = "buoy"
path = "bin/headless.rs"

[dependencies]
bevy = { workspace = true, features = ["dynamic_linking"] }
avian3d = { workspace = true }
uom = { workspace = true }
serde = { workspace = true }
# bevy_common_assets = { workspace = true }
bevy_repl = { workspace = true }
clap = { workspace = true }

[features]
default = ["dev"]
dev = [
    "bevy/dynamic_linking",
    "bevy/bevy_debug_stepping",
    "avian3d/bevy_diagnostic",
]
