[package]
name = "buoy_common"
version = "0.1.0"
edition = "2021"
description = "Common utilities for buoy simulation"

[lib]
path = "src/lib.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
