[package]
name = "buoy_common"
version = "0.1.0"
edition = "2024"
description = "Common utilities for buoy simulation"

[lib]
path = "src/lib.rs"

[dependencies]
bevy = { workspace = true }
uom = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
