[package]
name = "buoy-runtime"
version = "0.1.0"
description = "Runtime for the Buoy simulator"
edition = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
default-run = "buoy"

[[bin]]
name = "buoy"
path = "bin/main.rs"

[dependencies]
buoy-common = { path = "../buoy-common" }
buoy-physics = { path = "../buoy-physics" }
buoy-ui = { path = "../buoy-ui", optional = true }
bevy = { workspace = true }
avian3d = { workspace = true }
big_space = { workspace = true, optional = true }
bevy-inspector-egui = { version = "0.31.0", optional = true, features = [
    "highlight_changes",
] }
bevy_egui = { version = "0.34.1", optional = true }

[features]
default = ["dev"]
dev = ["buoy-common/dev", "buoy-physics/dev", "bevy/dynamic_linking"]
grid_space = ["buoy-common/grid_space", "buoy-physics/grid_space", "big_space"]
gui = ["buoy-ui", "bevy_egui", "big_space/camera"]
debug-ui = [
    "gui",
    "bevy/bevy_dev_tools",
    "buoy-ui/dev",
    "avian3d/debug-plugin",
    "bevy-inspector-egui",
]
