[package]
name = "buoy_physics"
version = "0.1.0"
edition = "2024"
description = "Core physics calculations for buoyant bodies"

[lib]
path = "src/lib.rs"

[dependencies]
bevy = { workspace = true }
nalgebra = { workspace = true }
serde = { workspace = true }
