name: Changelog

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"
  pull_request:
    types: [opened, synchronize, merged]

jobs:
  update-release:
    if: startsWith(github.ref, 'refs/tags/')
    name: Update Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-cliff
        uses: taiki-e/install-action@git-cliff

      - name: Generate release notes
        id: changelog
        run: |
          git-cliff --output RELEASE_NOTES.md --from-tag ${{ github.ref }}
          # Store release notes content for release update
          echo "release_notes_content<<EOF" >> $GITHUB_ENV
          cat RELEASE_NOTES.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: RELEASE_NOTES.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-pr:
    if: github.event_name == 'pull_request'
    name: Update Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-cliff
        uses: taiki-e/install-action@git-cliff

      - name: Generate release notes
        id: changelog
        run: |
          git-cliff --output RELEASE_NOTES.md ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
          # Store release notes content for PR update
          echo "release_notes_content<<EOF" >> $GITHUB_ENV
          cat RELEASE_NOTES.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Generate changelog
        run: |
          git-cliff --output CHANGELOG.md
          # Store changelog content for PR update
          echo "changelog_content<<EOF" >> $GITHUB_ENV
          cat CHANGELOG.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Add Release Notes Comment
        id: comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ env.release_notes_content }}
          edit-mode: replace
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changelog update
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git fetch origin
          git checkout ${{ github.head_ref }}
          git add CHANGELOG.md
          git commit -m "chore: update changelog"
          git push origin ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
