name: Changelog

on:
  pull_request:
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '.github/workflows/*.yaml'

jobs:
  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Get changed crates and versions
        id: versions
        run: |
          # Get changed files in this PR
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.sha }} -- "**/*.rs" "**/Cargo.toml" 2>/dev/null || echo "")

          # Find all crates with changes
          CHANGED_CRATES=()
          for file in $CHANGED_FILES; do
            dir=$(dirname "$file")
            while [ "$dir" != "." ]; do
              if [ -f "$dir/Cargo.toml" ]; then
                CRATE_NAME=$(grep -m1 '^name = ' "$dir/Cargo.toml" | cut -d'"' -f2)
                if [[ ! " ${CHANGED_CRATES[*]} " =~ " $CRATE_NAME " ]]; then
                  CHANGED_CRATES+=("$CRATE_NAME")
                fi
                break
              fi
              dir=$(dirname "$dir")
            done
          done

          # Generate version info with next bumps
          VERSION_INFO="## 游닍 Version Bumps\n\n"
          for member in $(cargo metadata --format-version=1 --no-deps | jq -r '.workspace_members[] | split(" ")[0]'); do
            current_version=$(cargo metadata --format-version=1 --no-deps | \
                           jq -r --arg m "$member" '.packages[] | select(.name == $m) | .version')

            if [[ " ${CHANGED_CRATES[*]} " =~ " $member " ]]; then
              # Calculate all version bumps with emojis
              major_version=$(echo $current_version | awk -F. '{$1 = $1 + 1; $2 = 0; $3 = 0; print $1"."$2"."$3}')
              minor_version=$(echo $current_version | awk -F. '{$2 = $2 + 1; $3 = 0; print $1"."$2"."$3}')
              patch_version=$(echo $current_version | awk -F. '{$3 = $3 + 1; print $1"."$2"."$3}')

              VERSION_INFO+="- **$member** ($current_version): 游댮 **$major_version** / "
              VERSION_INFO+="游리 **$minor_version** / "
              VERSION_INFO+="游릭 **$patch_version**\n"
            else
              VERSION_INFO+="- $member: $current_version\n"
            fi
          done

          # Add version bump legend
          VERSION_INFO+="\n**Legend**: 游댮 major | 游리 minor | 游릭 patch"

          echo "versions<<EOF" >> $GITHUB_OUTPUT
          echo -e "$VERSION_INFO" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --output CHANGELOG.md
        env:
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update PR with changelog
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ## 游늶 Changelog Preview

            ${{ steps.versions.outputs.versions }}

            <details>
            <summary>游닆 Full Changelog</summary>

            ```markdown
            $(cat CHANGELOG.md)
            ```
            </details>
